# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci

on:
  push:
    branches:
      - 'v[0-9]+'
  pull_request:
    branches:
      - 'v[0-9]+'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: git describe --always --tags
      - run: npm install
      - run: npm list -g --depth=0
      - run: npm run build:dev
      - run: find dist -ls
      - run: cd dist && tar -czf ../bundle.debug *
      - name: Archive bundle debug
        uses: actions/upload-artifact@v2
        with:
          name: debug
          retention-days: 2
          path: |
            bundle.debug
      - run: npm run build
      - run: find dist -ls
      - run: cd dist && tar -czf ../bundle *
      - name: Archive bundle
        uses: actions/upload-artifact@v2
        with:
          name: production
          retention-days: 2
          path: |
            bundle
